version: "3.8"
services:
  obfs4-bridge:
    image: thetorproject/obfs4-bridge:latest
    environment:
      # Exit with an error message if OR_PORT is unset or empty.
      - OR_PORT=${OR_PORT:?Env var OR_PORT is not set.}
      # Exit with an error message if PT_PORT is unset or empty.
      - PT_PORT=${PT_PORT:?Env var PT_PORT is not set.}
      # Exit with an error message if EMAIL is unset or empty.
      - EMAIL=${EMAIL:?Env var EMAIL is not set.}
      # Nickname with default value: "DockerObfs4Bridge"
      - NICKNAME=${NICKNAME:-DockerObfs4Bridge}
    env_file:
      - .env
    volumes:
      - data:/var/lib/tor
    ports:
      - ${OR_PORT}:${OR_PORT}
      - ${PT_PORT}:${PT_PORT}
    restart: unless-stopped

#  snowflake-proxy:
#      # TODO: need to modify firewall for this to work?
#      network_mode: host
#      image: thetorproject/snowflake-proxy:latest
#      container_name: snowflake-proxy
#      restart: unless-stopped

volumes:
  data:
    name: tor-datadir-${OR_PORT}-${PT_PORT}
